import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import NavBar from './components/navbar';
import Footer from './components/footer';
import ParticleBackground from './components/background';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio Site',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${nunito.variable} antialiased bg-gradient-to-tl from-pink-300 to-sky-300`}
        >
        <main className='flex flex-col relative z-1 min-h-screen'>
          <ParticleBackground/>
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}